name: Supabase Ping

on:
  schedule:
    - cron: '0 2 */3 * *' # Runs at 02:00 UTC on every 3 days.
  workflow_dispatch:

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Project
        run: |
          curl -X GET \
            "${{ secrets.SUPABASE_URL }}/rest/v1/points?select=id&limit=1" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json"
          echo "Ping successful at $(date)"